"""Add customer company status created_at

Revision ID: 04b480be4d1d
Revises: 7174ba930617
Create Date: 2026-09-03 17:51:24.501550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '04b480be4d1d'
down_revision: Union[str, Sequence[str], None] = '7174ba930617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'customers',
        sa.Column(
            'company',
            sa.String(length=255),
            nullable=True
        )
    )

    op.add_column(
        'customers',
        sa.Column(
            'status',
            sa.String(length=20),
            nullable=True
        )
    )

    op.add_column(
        'customers',
        sa.Column(
            'created_at',
            sa.DateTime(),
            nullable=True
        )
    )

    # Give existing customers default values
    op.execute(
        "UPDATE customers SET status = 'active' WHERE status IS NULL"
    )

    op.execute(
        "UPDATE customers SET created_at = CURRENT_TIMESTAMP "
        "WHERE created_at IS NULL"
    )

    # Make these columns required
    op.alter_column(
        'customers',
        'status',
        existing_type=sa.String(length=20),
        nullable=False
    )

    op.alter_column(
        'customers',
        'created_at',
        existing_type=sa.DateTime(),
        nullable=False
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'created_at')
    op.drop_column('customers', 'status')
    op.drop_column('customers', 'company')
    # ### end Alembic commands ###