"""Add ticket resolved_at

Revision ID: 1a021baf5b7a
Revises: 2b6cd67a2f95
Create Date: 2026-09-03 18:24:32.093843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '1a021baf5b7a'
down_revision: Union[str, Sequence[str], None] = '2b6cd67a2f95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###