"""Add ticket resolved_at

Revision ID: 2b6cd67a2f95
Revises: 04b480be4d1d
Create Date: 2026-09-03 18:22:29.220423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '2b6cd67a2f95'
down_revision: Union[str, Sequence[str], None] = '04b480be4d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'resolved_at')
    # ### end Alembic commands ###